/*
 *  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 *  Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *  SPDX-License-Identifier: Apache-2.0
 *  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 */

// This file is autogenerated using an internal tool that consumes the GameOn swagger document. Please do not edit manually.

import { ApiConfiguration } from '../http/apiClient';

/**
 * Helper class that instantiates an ApiClient implementation automatically resolving its
 * required ApiConfiguration.
 * @export
 * @class ApiClientFactory
 */
import { GameOnApiClient } from './gameOnApiClient';

export class ApiClientFactory {
    public apiConfiguration: ApiConfiguration;

    constructor(apiConfiguration: ApiConfiguration) {
        this.apiConfiguration = apiConfiguration;
    }

    /**
     * Gets an instance of GameOnApiClient.
     */
    public getGameOnApiClient(): GameOnApiClient {
        try {
            return new GameOnApiClient(this.apiConfiguration);
        } catch (e) {
            const factoryError = new Error(`ApiClientFactory Error while initializing GameOnApiClient: ${e.message}`);
            factoryError['name'] = 'ApiClientFactoryError';

            throw factoryError;
        }
    }
}
