version: 1
update_configs:
  # Keep package.json (& lockfiles) up to date as soon as
  # new versions are published to the npm registry
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    target_branch: "develop"
    default_reviewers:
      - "housed"
      - "superkew"
    default_labels:
      - "dependencies"
      - "dependabot"
    commit_message:
      prefix: "fix"
      prefix_development: "chore"
      include_scope: true

