#!/usr/bin/env bash
set -e

cd "$(dirname "$BASH_SOURCE")/.."

# see also ".mailmap" for how email addresses and names are deduplicated

{
    cat <<-'EOH'
# Skills GameOn SDK for Node.js Credits and Thanks
(This file is autogenerated using [update-credits.sh](tools/update-credits.sh).)

The Skills GameOn SDK for Node.js provides easy access to Amazon GameOn and creates higher-level methods, utilities, and examples that simplify the integration of GameOn features, like leaderboards, with Alexa skills.

Contributors to the Skills GameOn SDK for Node.js repository:
EOH
    echo
    git log --format='* %aN <%aE>' | LC_ALL=C.UTF-8 sort -uf
} > CREDITS.md
