#!/usr/bin/env bash
set -e

cd "$(dirname "$(readlink -f "$BASH_SOURCE")")/.."

# see also ".mailmap" for how email addresses and names are deduplicated

{
    cat <<-'EOH'
# Alexa GameOn SDK for Node.js Credits and Thanks
(This file is autogenerated using [update-credits.sh](tools/update-credits.sh).)

The Alexa GameOn SDK for Node.js provides easy access to all of the GameOn  APIs and creates higher level methods that simplify the most common actions skill developers need. The Alexa GameOn SDK for Node.js is currently licensed under [PML](LICENSE).

Thanks go to:
* [example name](https://github.com/example) <example@example.org>

Contributors to the Alexa GameOn SDK for Node.js repository:
EOH
    echo
    git log --format='* %aN <%aE>' | LC_ALL=C.UTF-8 sort -uf
} > CREDITS.md
